#!/bin/sh
[ -z "$(pidof systemd)" ] && \
  USING_SYSTEMD=false || \
  USING_SYSTEMD=true

case "$1" in
remove|purge)
	if $USING_SYSTEMD
	then
		systemctl stop xrdp
		systemctl daemon-reload
	else
		invoke-rc.d xrdp stop
		update-rc.d xrdp remove
	fi
	;;
esac
exit 0
